# Generated by Django 2.2.3 on 2020-12-12 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('word', models.CharField(max_length=120, unique=True)),
                ('language', models.CharField(choices=[('az', 'Azerbaijan'), ('en', 'English')], max_length=2)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WordTranslate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_word', to='dictapp.Word')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_word', to='dictapp.Word')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('source', 'target')},
            },
        ),
    ]
